name = "RiskBudgeting"
uuid = "a9f5bb6c-0632-44f9-9c01-5aa9e657c941"
authors = ["Kiar Fatah"]
version = "0.1.0"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1.7.1"
Documenter = "0.27.19"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
